apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
datadog:
  apiKey: ***********
  appKey: ********
  site: us5.datadoghq.com
  logs:
    enabled: true
    containerCollectAll: true
  kubelet:
    tlsVerify: false
    host:
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
providers:
  aks:
    enabled: true
